name: 05 - 1 - event filters and actvity types

on:
    pull_request:
        types:
            - closed
        branches:
            - doesnotexist


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "running whenever a pr is closed and the base branch is main"
