name: 10 - controlling the execution flow
run-name: execution flows

on:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: Whether or not the unit tests will pass
                default: true

jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            -   name: Lint and build
                run: echo "Linting and building"
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            -   name: unit tests
                run: echo "Running unit tests"
            -   name: Failing tests
                if: ${{ !inputs.pass-unit-tests }}
                run: exit 1
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs:
            -   lint-build
            -   unit-tests
        steps:
            -   name: deploy non prod
                run: echo "Deploying to non prod"
    e2e-tests:
        runs-on: ubuntu-latest
        needs:
            -   deploy-nonprod
        steps:
            -   name: end to end tests
                run: echo "running end to end tests"
    load-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            -   name: load tests
                run: echo "running load tests"
    deploy-prod:
        runs-on: ubuntu-latest
        needs:
            -   e2e-tests
            -   load-tests
        steps:
            -   name: deploy to prod
                run: echo "Deploying to prod"

