name: 05 - 1 - event filters and actvity types

on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "running whenever a pr is open or sycned and the base branch is main"
