name:  08 - using variables
run-name: "08 - Using variables"

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false


env:
    WORKFLOW_VAR: "I am a workflow env var"
jobs:
    echo:
        env:
            JOB_VAR: "I am a job var"
            OVERWRITTEN: "I have been overwrittem at the job level"
        runs-on: ubuntu-latest
        steps:
            -   name: print env variables
                env:
                    STEP_VAR: "I am a step var"
                    step_var2: "I am another step var"
                run: |
                    echo "Step env var ${{ env.STEP_VAR }}"
                    echo "Step env var2: $step_var2"
                    echo "Job env var: ${{ env.JOB_VAR }}"
                    echo "Workflow env var:  ${{ env.WORKFLOW_VAR }}"
                    echo "Job Overwritten var:  ${{ env.OVERWRITTEN }}"


