name: 11 - building blocks
run-name: Building blocks

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Skip deployment and only print build output
        default: false
      target:
        type: environment
        required: true
        description: which environment the workflow will target
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        description: which tag to use
        default: v3

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
          - name: build
            run: echo "Building from tag ${{ inputs.tag }}"
    deploy:
      runs-on: ubuntu-latest
      if: ${{ !inputs.dry-run }}
      environment: ${{ inputs.target }}
      steps:
          - name: deploy
            run: echo "Deploying to ${{ inputs.target }}"
