name: 13 - Using caching


on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: Should we execute the cache step
                type: boolean
                default: true
            node-version:
                description: Node version
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                    - 22.x
                default: 20.x


jobs:
    install-deps:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        outputs:
            deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
        steps:
            -   name: checkout code
                uses: actions/checkout@v4
            -   name: setup node
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ inputs.node-version }}
            -   name: Calculate cache key
                id: cache-key
                run: |
                    echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package.lock.json')}}"
            -   name: download cached dependencies
                uses: actions/cache@v3
                if:   ${{ inputs.use-cache }}
                id: cache
                with:
                    key: ${{ steps.cache-key.outputs.CACHE_KEY }}
                    path: 13-caching/react-app/node_modules
            -   name: Install dependencies
                if: steps.cache.outputs.cache-hit != 'true'
                run:  npm ci
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        needs: install-deps
        steps:
            -   name: checkout code
                uses: actions/checkout@v4
            -   name: setup node
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ inputs.node-version }}
            -   name: download cached dependencies
                uses: actions/cache@v3
                if:   ${{ inputs.use-cache }}
                id: cache
                with:
                    key: ${{ needs.install-deps.outputs.deps-cache-key }}
                    path: 13-caching/react-app/node_modules
            -   name: Install dependencies
                if: steps.cache.outputs.cache-hit != 'true'
                run:  npm ci
            -   name: Testing
                run:  npm test
            -   name: Building
                run:  npm run build
            -   name: Deploy to non prod
                run: echo "Deploying to non prod"


